### PR TITLE
Add export_pushing_battles.py

### PR DESCRIPTION
**Pull request by RFabionar**
Collects and exports all Super Scout pushing battles to a CSV file.

### CODE REVIEW

**Review by cartervluck — APPROVED** [review]
Peer review

**Review by mckennalincoln — APPROVED** [review]
Buddy review

**Review by ghost — DISMISSED** [review]

**Review by Ethan-Talbert — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by EmilyTLin — APPROVED** [review]
Peer reviewed

**Review by Ethan-Talbert — APPROVED** [review]
Buddy Review

**Pull request merged**
